<a href="https://colab.research.google.com/github/AugustvonMackensen/AI_colab/blob/main/1_2_pytorch_basic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **PyTorch Tensor Basic Usage**
- Create Tensor
- Indexing, Joining, Slicing
- Initialization
- Math Operations

# **1. Create Tensor**
1) random numbers

In [59]:
# 새 노트에서 런타임 > GPU 로 다시 지정함
import torch

# torch.rand(sizes) --> 0에서 1 사이의 실수값을 랜덤하게 발생함
# sizes : 1차원 개수 or 2차원 행렬 갯수 등으로 지정
# 0과 1 사이의 실수형 숫자를 균등하게 생성
x = torch.rand(2, 3)
x

tensor([[0.7223, 0.2037, 0.9776],
        [0.9114, 0.6989, 0.0788]])

In [60]:
# torch.randn(sizes) --> Z(0, 1)
# 평균이 0이고, 표준편차가 1인 가우시안 정규분포를 이용해서 생성
x = torch.randn(2, 3)
x

tensor([[ 1.0667, -1.1885, -0.0438],
        [-0.3100,  0.4412, -0.4390]])

In [61]:
# torch.randperm(n) --> permutation of 0 ~ n
x = torch.randperm(5)
x

tensor([3, 2, 0, 1, 4])

**랜덤한 값을 가지는 텐서 생성시키는 함수들**
1. torch.rand() : 0과 1사이의 숫자를 균등하게 생성
2. torch.rand_like() : 사이즈를 튜플로 입력하지 않고, 기존의 텐서와 같은 구조를 만들때 사용
3. torch.randn() : 평균이 0이고 표준편차가 1인 가우시안 정규분포를 이용해 값 생성
4. torch.randn_like() : 사이즈를 튜플로 지정하지 않고 기존의 텐서를 이용
5. torch.randint() : 주어진 범위 내의 정수를 균등하게 생성. 자료형은 torch.float32
6. torch.randint_like()
7. torch.randperm() : 주어진 범위 내의 정수를 랜덤하게 생성


# **2) zeros, ones, arange**

In [62]:
# torch.zeros(2, 3) --> [[0,0,0], [0,0,0]]
x = torch.zeros(2, 3)
x

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [63]:
# torch.ones(2, 3) --> [[1,1,1], [1,1,1]]
x = torch.ones(2, 3)
x

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [64]:
# torch.arange(start, end, strp=1)
x = torch.arange(0, 3, step=0.5)
x

tensor([0.0000, 0.5000, 1.0000, 1.5000, 2.0000, 2.5000])

# **3) Tensor Data Type**

In [65]:
# torch.FloatTensor(size | list)
x = torch.FloatTensor(2, 3)
x

tensor([[1.4759e+10, 0.0000e+00, 1.0000e+00],
        [1.5000e+00, 2.0000e+00, 2.5000e+00]])

In [66]:
x = torch.FloatTensor([12, 35])
x

tensor([12., 35.])

In [67]:
# tensor.type_as(tensor_type)
# 기존 텐서의 값의 자료형을 바꿀 때 사용
x = x.type_as(torch.IntTensor())
x

tensor([12, 35], dtype=torch.int32)

# **4) Numpy to Tensor, Tensor to Numpy**

In [68]:
import numpy as np

# torch.from_numpy(ndarray) --> tensor
x1 = np.ndarray(shape=(2, 3), dtype=int, buffer=np.array([1,2,3,4,5,6]))
x1
x2 = torch.from_numpy(x1)
x2

tensor([[1, 2, 3],
        [4, 5, 6]])

In [69]:
# torch.numpy() --> ndarray
x3 = x2.numpy()
x3

array([[1, 2, 3],
       [4, 5, 6]])

# **5) Tensor on CPU & GPU**

In [70]:
x = torch.FloatTensor(([1,2,3],[4,5,6]))
x
x_gpu = x.cuda()
x_gpu

x_cpu = x_gpu.cpu()
x_cpu

tensor([[1., 2., 3.],
        [4., 5., 6.]])

6) Tensor Size

In [71]:
# tensor객체.size() --> 인덱스값
x = torch.FloatTensor(10, 12, 3, 3) # start, end-1, row, col
x
x.size() # torch.size([10, 12, 3, 3])
x.size()[:] # torch.size([10, 12, 3, 3]) 

torch.Size([10, 12, 3, 3])

# **2. Indexing, Slicing, Joining**
**1) Indexing**

In [72]:
# torch.index_select(input, dim, index)
# dim == 행값, index == 열에 대한 인덱싱
x = torch.rand(4, 3)
out = torch.index_select(x, 0, torch.LongTensor([0, 3]))

x, out

(tensor([[0.5142, 0.6679, 0.4964],
         [0.3784, 0.0650, 0.8284],
         [0.0234, 0.5295, 0.6574],
         [0.8071, 0.5419, 0.0713]]), tensor([[0.5142, 0.6679, 0.4964],
         [0.8071, 0.5419, 0.0713]]))

In [73]:
# python indexing 사용 가능
x[:, 0] # 모든 행의 0열 값들
x[0, :] # 0행의 모든값들
x[0:2, 0:2] # 0~1행, 0~1열까지의 값들

tensor([[0.5142, 0.6679],
        [0.3784, 0.0650]])

In [74]:
# torch.masked_select(input, mask)
x = torch.randn(2, 3)
x
mask = torch.ByteTensor([[0, 0, 1], [0, 1, 0]])
out = torch.masked_select(x, mask)
x, mask, out

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: UserWarning: masked_select received a mask with dtype torch.uint8, this behavior is now deprecated,please use a mask with dtype torch.bool instead. (Triggered internally at  ../aten/src/ATen/native/TensorAdvancedIndexing.cpp:1664.)
  """


(tensor([[-0.1748, -0.1666, -0.0964],
         [ 0.2733, -0.6178,  0.4085]]), tensor([[0, 0, 1],
         [0, 1, 0]], dtype=torch.uint8), tensor([-0.0964, -0.6178]))

**2) Joining**

In [75]:
# torch.cat(seq, dim=0)

x = torch.FloatTensor([[1,2,3],[4,5,6]])
y = torch.FloatTensor([[-1,-2,-3],[-4,-5,-6]])

z1 = torch.cat([x,y], dim=0) # dim=0, 아래에 합쳐짐
z2 = torch.cat([x,y], dim=1) # dim=1, 오른쪽에 합쳐짐

x, y, z1, z2 # z1, z2 확인해보려면 print로 보시오.

(tensor([[1., 2., 3.],
         [4., 5., 6.]]), tensor([[-1., -2., -3.],
         [-4., -5., -6.]]), tensor([[ 1.,  2.,  3.],
         [ 4.,  5.,  6.],
         [-1., -2., -3.],
         [-4., -5., -6.]]), tensor([[ 1.,  2.,  3., -1., -2., -3.],
         [ 4.,  5.,  6., -4., -5., -6.]]))

In [76]:
# torch.stack(sequence, dim=0) --> 새로운 차원으로 추가
x_stack = torch.stack([x, x, x, x], dim=0) # (4,2,3) 모양

x_stack

tensor([[[1., 2., 3.],
         [4., 5., 6.]],

        [[1., 2., 3.],
         [4., 5., 6.]],

        [[1., 2., 3.],
         [4., 5., 6.]],

        [[1., 2., 3.],
         [4., 5., 6.]]])

**3) Slicing**

In [77]:
# torch.chunk(tensor, chunks, dim=0)
x_1, x_2 = torch.chunk(z1, 2, dim=0) # dim 이 0이면 행을 2개로 분할
y_1, y_2, y_3 = torch.chunk(z1, 3, dim=1) #dim 이 1이면 열을 3개로 분할

z1, x_1, x_2, y_1, y_2, y_3

(tensor([[ 1.,  2.,  3.],
         [ 4.,  5.,  6.],
         [-1., -2., -3.],
         [-4., -5., -6.]]), tensor([[1., 2., 3.],
         [4., 5., 6.]]), tensor([[-1., -2., -3.],
         [-4., -5., -6.]]), tensor([[ 1.],
         [ 4.],
         [-1.],
         [-4.]]), tensor([[ 2.],
         [ 5.],
         [-2.],
         [-5.]]), tensor([[ 3.],
         [ 6.],
         [-3.],
         [-6.]]))

In [78]:
# torch.split(tensor, split_size, dim=0)
x1, x2 = torch.split(z1, 2, dim=0)
_, y1 = torch.split(z1, 2, dim=1) # 3개 열을 2개로 분할

z1, x1, x2, y1

(tensor([[ 1.,  2.,  3.],
         [ 4.,  5.,  6.],
         [-1., -2., -3.],
         [-4., -5., -6.]]), tensor([[1., 2., 3.],
         [4., 5., 6.]]), tensor([[-1., -2., -3.],
         [-4., -5., -6.]]), tensor([[ 3.],
         [ 6.],
         [-3.],
         [-6.]]))

**4) Squeezing**

In [79]:
# torch.squeeze(input, dim=None) --> 숫자가 1인 차원을 제거
x1 = torch.FloatTensor(10, 1, 3, 14)
# 차원(dimension)의 개념
# 10 : batch size (데이터 한 묶음당 들어있는 데이터(x,y)쌍 갯수)
# 1 : channel size
# 3 : width image size
# 14 : height image size

x2 = torch.squeeze(x1)

x1.size(), x2.size()

(torch.Size([10, 1, 3, 14]), torch.Size([10, 3, 14]))

In [80]:
# torch.unsqueeze(input, dim=None) --> 숫자가 1인 차원을 추가
x1 = torch.FloatTensor(10, 3, 4)
x2 = torch.unsqueeze(x1, dim=0) # dim이 0이면, 첫번째 위치에 추가

x1.size(), x2.size()

(torch.Size([10, 3, 4]), torch.Size([1, 10, 3, 4]))

# **3. Initialization**

In [81]:
import torch.nn.init as init

x1 = init.uniform(torch.FloatTensor(3, 4), a=0, b=9) # a에서 b까지의 값으로 초기화
x2 = init.normal(torch.FloatTensor(3, 4), std=0.2) # 표준편차 0.2를 적용 초기화
x3 = init.constant(torch.FloatTensor(3, 4), 3.145) # 지정된 상수 값으로 초기화

x1, x2, x3

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: UserWarning: nn.init.uniform is now deprecated in favor of nn.init.uniform_.
  This is separate from the ipykernel package so we can avoid doing imports until
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: UserWarning: nn.init.normal is now deprecated in favor of nn.init.normal_.
  after removing the cwd from sys.path.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: UserWarning: nn.init.constant is now deprecated in favor of nn.init.constant_.
  """


(tensor([[2.0158, 7.3316, 7.9449, 1.0579],
         [5.5617, 6.1086, 2.1596, 3.7927],
         [0.7437, 2.0766, 5.3414, 2.0026]]),
 tensor([[ 0.0431, -0.0426, -0.1647,  0.3067],
         [ 0.3010,  0.1073,  0.3981, -0.3276],
         [-0.1460, -0.1736,  0.2445, -0.1464]]),
 tensor([[3.1450, 3.1450, 3.1450, 3.1450],
         [3.1450, 3.1450, 3.1450, 3.1450],
         [3.1450, 3.1450, 3.1450, 3.1450]]))

# **4. Math Operations**

**1) arithmetic operations**

In [82]:
# torch.add()
x1 = torch.FloatTensor([[1,2,3], [4,5,6]])
x2 = torch.FloatTensor([[1,2,3], [4,5,6]])
x_add = torch.add(x1, x2)
x1, x2, x_add, x1 + x2, x1 - x2

(tensor([[1., 2., 3.],
         [4., 5., 6.]]), tensor([[1., 2., 3.],
         [4., 5., 6.]]), tensor([[ 2.,  4.,  6.],
         [ 8., 10., 12.]]), tensor([[ 2.,  4.,  6.],
         [ 8., 10., 12.]]), tensor([[0., 0., 0.],
         [0., 0., 0.]]))

In [83]:
# torch.add() : broadcastion (숫자와의 연산)
x3 = torch.add(x1, 10)

x3, x1 + 10, x2 - 10

(tensor([[11., 12., 13.],
         [14., 15., 16.]]), tensor([[11., 12., 13.],
         [14., 15., 16.]]), tensor([[-9., -8., -7.],
         [-6., -5., -4.]]))

In [84]:
# torch.mul() 곱하기
x3 = torch.mul(x1, x2)

x3, x1 * x2

(tensor([[ 1.,  4.,  9.],
         [16., 25., 36.]]), tensor([[ 1.,  4.,  9.],
         [16., 25., 36.]]))

In [85]:
x3 = torch.mul(x1, 10)

x3, x1 * 10

(tensor([[10., 20., 30.],
         [40., 50., 60.]]), tensor([[10., 20., 30.],
         [40., 50., 60.]]))

In [86]:
# torch.div() 나누기한 몫
x3 = torch.div(x1, 5)

x1, x3, x1 / 5

(tensor([[1., 2., 3.],
         [4., 5., 6.]]), tensor([[0.2000, 0.4000, 0.6000],
         [0.8000, 1.0000, 1.2000]]), tensor([[0.2000, 0.4000, 0.6000],
         [0.8000, 1.0000, 1.2000]]))

**2) Other Math Operations**

In [87]:
# torch.pow(input, exponent)
x1 = torch.FloatTensor(3,4)

x1, torch.pow(x1, 2), x1 ** 2

(tensor([[4.9071e+11, 0.0000e+00, 6.0000e-01, 8.0000e-01],
         [1.0000e+00, 1.2000e+00, 0.0000e+00, 2.3750e+00],
         [0.0000e+00, 2.3125e+00, 0.0000e+00, 2.2500e+00]]),
 tensor([[2.4080e+23, 0.0000e+00, 3.6000e-01, 6.4000e-01],
         [1.0000e+00, 1.4400e+00, 0.0000e+00, 5.6406e+00],
         [0.0000e+00, 5.3477e+00, 0.0000e+00, 5.0625e+00]]),
 tensor([[2.4080e+23, 0.0000e+00, 3.6000e-01, 6.4000e-01],
         [1.0000e+00, 1.4400e+00, 0.0000e+00, 5.6406e+00],
         [0.0000e+00, 5.3477e+00, 0.0000e+00, 5.0625e+00]]))

In [88]:
# torch.exp(tensor, out=None) : exponential 연산
# y = e의 x제곱 구하기
x1 = torch.FloatTensor(3,4)
out = torch.exp(x1)

x1, out

(tensor([[4.9074e+11, 0.0000e+00, 3.6000e-01, 6.4000e-01],
         [1.0000e+00, 1.4400e+00, 0.0000e+00, 5.6406e+00],
         [0.0000e+00, 5.3477e+00, 0.0000e+00, 5.0625e+00]]),
 tensor([[     inf,   1.0000,   1.4333,   1.8965],
         [  2.7183,   4.2207,   1.0000, 281.6387],
         [  1.0000, 210.1153,   1.0000, 157.9850]]))

In [89]:
# torch.log(input, out=None) : 자연로그
out = torch.log(x)
x1, out

(tensor([[4.9074e+11, 0.0000e+00, 3.6000e-01, 6.4000e-01],
         [1.0000e+00, 1.4400e+00, 0.0000e+00, 5.6406e+00],
         [0.0000e+00, 5.3477e+00, 0.0000e+00, 5.0625e+00]]),
 tensor([[0.0000, 0.6931, 1.0986],
         [1.3863, 1.6094, 1.7918]]))

**3) Matrix operations**

In [90]:
# torch.mm(mat1, mat2) -> Matrix multiplication (행렬곱)
x1 = torch.FloatTensor(3,4)
x2 = torch.FloatTensor(4,5)
out = torch.mm(x1, x2)
x1, x2, out

(tensor([[1.4763e+10, 0.0000e+00, 1.0986e+00, 1.3863e+00],
         [1.6094e+00, 1.7918e+00, 0.0000e+00, 5.6406e+00],
         [0.0000e+00, 5.3477e+00, 0.0000e+00, 5.0625e+00]]),
 tensor([[0.0000e+00, 0.0000e+00, 1.0930e-43, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 1.1021e+24],
         [7.7052e+31, 1.9447e+31, 2.1715e-18, 2.3081e-12, 1.8590e+34],
         [7.7767e+31, 1.7181e+19, 1.8990e+28, 1.5766e-19, 1.4586e-19]]),
 tensor([[1.9246e+32, 2.1365e+31, 2.6325e+28, 2.5357e-12, 2.0423e+34],
         [4.3865e+32, 9.6912e+19, 1.0711e+29, 8.8931e-19, 1.9747e+24],
         [3.9369e+32, 8.6979e+19, 9.6135e+28, 7.9816e-19, 5.8938e+24]]))

In [91]:
# torch.bmm(batch1, batch2) --> batch 행렬 연산
# 맨 앞의 batch는 차원을 유지하면서 뒤 요소들의 행렬곱 연산함
x1 = torch.FloatTensor(10, 3, 4)
x2 = torch.FloatTensor(10, 4, 5)
out = torch.bmm(x1, x2)
out.size()

torch.Size([10, 3, 5])

In [92]:
# torch.dot(tensor1, tensor2) : 벡터의 내적을 구함
x1 = torch.FloatTensor([1,2,3,4])
x2 = torch.FloatTensor([2,3,4,5])

torch.dot(x1,x2)

tensor(40.)

In [96]:
# torch.t(matrix) : transposed matrix(텐서의 전치연산)
# 행과 열 서로 바꿈

x1 = torch.FloatTensor(3,4)

x1, x1.t()

(tensor([[4.9487e+11, 0.0000e+00, 5.1848e-44, 0.0000e+00],
         [       nan, 1.9904e+00, 3.0478e+32, 4.5925e+24],
         [1.7448e+22, 7.5878e+31, 1.8522e+28, 1.8057e+28]]),
 tensor([[4.9487e+11,        nan, 1.7448e+22],
         [0.0000e+00, 1.9904e+00, 7.5878e+31],
         [5.1848e-44, 3.0478e+32, 1.8522e+28],
         [0.0000e+00, 4.5925e+24, 1.8057e+28]]))

In [94]:
# torch.transpose(input, dim_0, dim_1)
# 바꿀 차원을 2개 지정함
# 텐서의 내부 차원간 바꾸기
x1 = torch.FloatTensor(10, 3, 4)

# 1차원과 2차원을 서로 바꿈
x1.size(), torch.transpose(x1, 1, 2).size(), x1.transpose(1, 2).size()

(torch.Size([10, 3, 4]), torch.Size([10, 4, 3]), torch.Size([10, 4, 3]))

In [97]:
# torch.eig(input, eigenvectors=False)
# 고유값(eigen_value), 고유벡터(eigen_vector) 반환
x1 = torch.FloatTensor(4,4)

x1, torch.eig(x1, True)

(tensor([[4.9487e+11, 0.0000e+00, 2.3694e-38, 3.0478e+32],
         [4.5925e+24, 1.7448e+22, 7.5878e+31, 1.8522e+28],
         [1.8057e+28, 7.1901e+28, 6.2706e+22, 4.7428e+30],
         [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00]]),
 torch.return_types.eig(
 eigenvalues=tensor([[ 2.3358e+30,  0.0000e+00],
         [-2.3358e+30,  0.0000e+00],
         [ 4.9487e+11,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00]]),
 eigenvectors=tensor([[ 0.0000e+00,  0.0000e+00,  9.6988e-01, -9.6988e-01],
         [ 9.9953e-01,  9.9953e-01, -2.4357e-01,  2.4357e-01],
         [ 3.0768e-02, -3.0768e-02, -5.8261e-08,  5.8005e-08],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  1.5748e-21]])))