<a href="https://colab.research.google.com/github/AugustvonMackensen/AI_colab/blob/main/1_2_pytorch_basic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **PyTorch Tensor Basic Usage**
- Create Tensor
- Indexing, Joining, Slicing
- Initialization
- Math Operations

# **1. Create Tensor**
1) random numbers

In [ ]:
# 새 노트에서 런타임 > GPU 로 다시 지정함
import torch

# torch.rand(sizes) --> 0에서 1 사이의 실수값을 랜덤하게 발생함
# sizes : 1차원 개수 or 2차원 행렬 갯수 등으로 지정
# 0과 1 사이의 실수형 숫자를 균등하게 생성
x = torch.rand(2, 3)
x

tensor([[0.1407, 0.7833, 0.4957],
        [0.4202, 0.1787, 0.7787]])

In [ ]:
# torch.randn(sizes) --> Z(0, 1)
# 평균이 0이고, 표준편차가 1인 가우시안 정규분포를 이용해서 생성
x = torch.randn(2, 3)
x

tensor([[-0.2561, -0.3439, -0.1149],
        [-1.6778, -0.5819, -0.8236]])

In [ ]:
# torch.randperm(n) --> permutation of 0 ~ n
x = torch.randperm(5)
x

tensor([3, 4, 0, 1, 2])

**랜덤한 값을 가지는 텐서 생성시키는 함수들**
1. torch.rand() : 0과 1사이의 숫자를 균등하게 생성
2. torch.rand_like() : 사이즈를 튜플로 입력하지 않고, 기존의 텐서와 같은 구조를 만들때 사용
3. torch.randn() : 평균이 0이고 표준편차가 1인 가우시안 정규분포를 이용해 값 생성
4. torch.randn_like() : 사이즈를 튜플로 지정하지 않고 기존의 텐서를 이용
5. torch.randint() : 주어진 범위 내의 정수를 균등하게 생성. 자료형은 torch.float32
6. torch.randint_like()
7. torch.randperm() : 주어진 범위 내의 정수를 랜덤하게 생성


# **2) zeros, ones, arange**

In [ ]:
# torch.zeros(2, 3) --> [[0,0,0], [0,0,0]]
x = torch.zeros(2, 3)
x

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
# torch.ones(2, 3) --> [[1,1,1], [1,1,1]]
x = torch.ones(2, 3)
x

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
# torch.arange(start, end, strp=1)
x = torch.arange(0, 3, step=0.5)
x

tensor([0.0000, 0.5000, 1.0000, 1.5000, 2.0000, 2.5000])

# **3) Tensor Data Type**

In [7]:
# torch.FloatTensor(size | list)
x = torch.FloatTensor(2, 3)
x

tensor([[4.7701e-35, 0.0000e+00, 3.7835e-44],
        [0.0000e+00,        nan, 2.5000e+00]])

In [9]:
x = torch.FloatTensor([12, 35])
x

tensor([12., 35.])

In [10]:
# tensor.type_as(tensor_type)
# 기존 텐서의 값의 자료형을 바꿀 때 사용
x = x.type_as(torch.IntTensor())
x

tensor([12, 35], dtype=torch.int32)

# **4) Numpy to Tensor, Tensor to Numpy**

In [12]:
import numpy as np

# torch.from_numpy(ndarray) --> tensor
x1 = np.ndarray(shape=(2, 3), dtype=int, buffer=np.array([1,2,3,4,5,6]))
x1
x2 = torch.from_numpy(x1)
x2

tensor([[1, 2, 3],
        [4, 5, 6]])

In [13]:
# torch.numpy() --> ndarray
x3 = x2.numpy()
x3

array([[1, 2, 3],
       [4, 5, 6]])

# **5) Tensor on CPU & GPU**

In [18]:
x = torch.FloatTensor(([1,2,3],[4,5,6]))
x
x_gpu = x.cuda()
x_gpu

x_cpu = x_gpu.cpu()
x_cpu

tensor([[1., 2., 3.],
        [4., 5., 6.]])

6) Tensor Size

In [21]:
# tensor객체.size() --> 인덱스값
x = torch.FloatTensor(10, 12, 3, 3) # start, end-1, row, col
x
x.size() # torch.size([10, 12, 3, 3])
x.size()[:] # torch.size([10, 12, 3, 3]) 

torch.Size([10, 12, 3, 3])

# **2. Indexing, Slicing, Joining**
**1) Indexing**

In [22]:
# torch.index_select(input, dim, index)
# dim == 행값, index == 열에 대한 인덱싱
x = torch.rand(4, 3)
out = torch.index_select(x, 0, torch.LongTensor([0, 3]))

x, out

(tensor([[0.3421, 0.1026, 0.7050],
         [0.1466, 0.2202, 0.4914],
         [0.3256, 0.1677, 0.3894],
         [0.8934, 0.0196, 0.1062]]), tensor([[0.3421, 0.1026, 0.7050],
         [0.8934, 0.0196, 0.1062]]))

In [25]:
# python indexing 사용 가능
x[:, 0] # 모든 행의 0열 값들
x[0, :] # 0행의 모든값들
x[0:2, 0:2] # 0~1행, 0~1열까지의 값들

tensor([[0.3421, 0.1026],
        [0.1466, 0.2202]])

In [28]:
# torch.masked_select(input, mask)
x = torch.randn(2, 3)
x
mask = torch.ByteTensor([[0, 0, 1], [0, 1, 0]])
out = torch.masked_select(x, mask)
x, mask, out

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: UserWarning: masked_select received a mask with dtype torch.uint8, this behavior is now deprecated,please use a mask with dtype torch.bool instead. (Triggered internally at  ../aten/src/ATen/native/TensorAdvancedIndexing.cpp:1664.)
  """


(tensor([[ 0.2777,  1.0669,  1.1946],
         [-0.5515,  0.7418,  0.1002]]), tensor([[0, 0, 1],
         [0, 1, 0]], dtype=torch.uint8), tensor([1.1946, 0.7418]))

**2) Joining**

In [32]:
# torch.cat(seq, dim=0)

x = torch.FloatTensor([[1,2,3],[4,5,6]])
y = torch.FloatTensor([[-1,-2,-3],[-4,-5,-6]])

z1 = torch.cat([x,y], dim=0) # dim=0, 아래에 합쳐짐
z2 = torch.cat([x,y], dim=1) # dim=1, 오른쪽에 합쳐짐

x, y, z1, z2 # z1, z2 확인해보려면 print로 보시오.

(tensor([[1., 2., 3.],
         [4., 5., 6.]]), tensor([[-1., -2., -3.],
         [-4., -5., -6.]]), tensor([[ 1.,  2.,  3.],
         [ 4.,  5.,  6.],
         [-1., -2., -3.],
         [-4., -5., -6.]]), tensor([[ 1.,  2.,  3., -1., -2., -3.],
         [ 4.,  5.,  6., -4., -5., -6.]]))

In [34]:
# torch.stack(sequence, dim=0) --> 새로운 차원으로 추가
x_stack = torch.stack([x, x, x, x], dim=0) # (4,2,3) 모양

x_stack

tensor([[[1., 2., 3.],
         [4., 5., 6.]],

        [[1., 2., 3.],
         [4., 5., 6.]],

        [[1., 2., 3.],
         [4., 5., 6.]],

        [[1., 2., 3.],
         [4., 5., 6.]]])