<a href="https://colab.research.google.com/github/AugustvonMackensen/AI_colab/blob/main/1_2_pytorch_basic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **PyTorch Tensor Basic Usage**
- Create Tensor
- Indexing, Joining, Slicing
- Initialization
- Math Operations

# **1. Create Tensor**
1) random numbers

In [1]:
# 새 노트에서 런타임 > GPU 로 다시 지정함
import torch

# torch.rand(sizes) --> 0에서 1 사이의 실수값을 랜덤하게 발생함
# sizes : 1차원 개수 or 2차원 행렬 갯수 등으로 지정
# 0과 1 사이의 실수형 숫자를 균등하게 생성
x = torch.rand(2, 3)
x

tensor([[0.1407, 0.7833, 0.4957],
        [0.4202, 0.1787, 0.7787]])

In [2]:
# torch.randn(sizes) --> Z(0, 1)
# 평균이 0이고, 표준편차가 1인 가우시안 정규분포를 이용해서 생성
x = torch.randn(2, 3)
x

tensor([[-0.2561, -0.3439, -0.1149],
        [-1.6778, -0.5819, -0.8236]])

In [3]:
# torch.randperm(n) --> permutation of 0 ~ n
x = torch.randperm(5)
x

tensor([3, 4, 0, 1, 2])

**랜덤한 값을 가지는 텐서 생성시키는 함수들**
1. torch.rand() : 0과 1사이의 숫자를 균등하게 생성
2. torch.rand_like() : 사이즈를 튜플로 입력하지 않고, 기존의 텐서와 같은 구조를 만들때 사용
3. torch.randn() : 평균이 0이고 표준편차가 1인 가우시안 정규분포를 이용해 값 생성
4. torch.randn_like() : 사이즈를 튜플로 지정하지 않고 기존의 텐서를 이용
5. torch.randint() : 주어진 범위 내의 정수를 균등하게 생성. 자료형은 torch.float32
6. torch.randint_like()
7. torch.randperm() : 주어진 범위 내의 정수를 랜덤하게 생성


# **2) zeros, ones, arange**

In [4]:
# torch.zeros(2, 3) --> [[0,0,0], [0,0,0]]
x = torch.zeros(2, 3)
x

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [5]:
# torch.ones(2, 3) --> [[1,1,1], [1,1,1]]
x = torch.ones(2, 3)
x

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [6]:
# torch.arange(start, end, strp=1)
x = torch.arange(0, 3, step=0.5)
x

tensor([0.0000, 0.5000, 1.0000, 1.5000, 2.0000, 2.5000])