<a href="https://colab.research.google.com/github/AugustvonMackensen/AI_colab/blob/main/2_3_LR_Variable.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **2_3_LR_Variable.ipynb**

**Variable & Automatic Gradient Calculation**
- Tensor vs Variable
- Graph and Gradient


In [3]:
import torch # Facebook에서 개발함
from torch.autograd import Variable

# **2. Tensor & Variable**

**1) Declaration**

In [10]:
x_tensor = torch.Tensor(3,4)
x_tensor

tensor([[1.5101e-35, 0.0000e+00, 3.7835e-44, 0.0000e+00],
        [       nan, 0.0000e+00, 1.3733e-14, 6.4069e+02],
        [4.3066e+21, 1.1824e+22, 4.3066e+21, 6.3828e+28]])

In [11]:
x_variable = Variable(x_tensor)
x_variable

tensor([[1.5101e-35, 0.0000e+00, 3.7835e-44, 0.0000e+00],
        [       nan, 0.0000e+00, 1.3733e-14, 6.4069e+02],
        [4.3066e+21, 1.1824e+22, 4.3066e+21, 6.3828e+28]])

Variable은 autogradient 가능함<br>
Pytorch 0.4 이상 버전에서는 Tensor에 Variable이 통합되고,<br>
Variable은 deprecated 됨<br>
Tensor만 사용함<br>

**2) Variables of a Variable**


In [12]:
# data 속성
x_variable.data

tensor([[1.5101e-35, 0.0000e+00, 3.7835e-44, 0.0000e+00],
        [       nan, 0.0000e+00, 1.3733e-14, 6.4069e+02],
        [4.3066e+21, 1.1824e+22, 4.3066e+21, 6.3828e+28]])

In [6]:
# grad 속성 : 값에 대한 gradient
# Variable 생성시 초기화되면서, gradient도 같이 정의됨
print(x_variable.grad)

None


In [7]:
# requires_grad 속성 : 값에 대한 gradient 요구시 사용
print(x_variable.requires_grad) # 속성값 확인 : False
# gradient 가 계산이 안된 상태임

False


In [13]:
# gradient 에 대한 연산을 모두 추적함 : True
x_variable = Variable(x_tensor, requires_grad=True)
print(x_variable.requires_grad)
print(x_variable.data)
print(x_variable.grad)

True
tensor([[1.5101e-35, 0.0000e+00, 3.7835e-44, 0.0000e+00],
        [       nan, 0.0000e+00, 1.3733e-14, 6.4069e+02],
        [4.3066e+21, 1.1824e+22, 4.3066e+21, 6.3828e+28]])
None


In [20]:
# volatile 속성 : 최소 메모리 사용에 대한 설정
# requires_grad가 False이면, volatile 도 자동 False가 됨
x_variable = Variable(x_tensor, volatile=True)
print(x_variable.grad)
print(x_variable.volatile)
print(x_variable.requires_grad)

None
False
False


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: UserWarning: volatile was removed and now has no effect. Use `with torch.no_grad():` instead.
  This is separate from the ipykernel package so we can avoid doing imports until
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: UserWarning: volatile was removed (Variable.volatile is always False)
  """


# **3. Graph & Variables**

In [25]:
# Create graph
x = Variable(torch.FloatTensor(3, 4), requires_grad=True)
y = x ** 2 + 4 * x
z = 2 * y + 3

print(x.requires_grad)
print(y.requires_grad)
print(z.requires_grad)

True
True
True


In [26]:
# backward(gradient, retain_graph, create_graph, retain_variables)
# 현재 값 w, r, t, graph에 대한 gradient 계산 함수임
# 역전파 알고리즘 적용 계산함수

# 위의 z 값으로 x의 gradient 를 계산해 냄
loss = torch.FloatTensor(3, 4)
z.backward(loss)

print(x.grad)
print(y.grad)
print(z.grad)

tensor([[8.7099e-37, 0.0000e+00, 9.4167e-42, 9.8651e-42],
        [1.0403e-41, 3.5873e-42, 1.0762e-41, 4.1254e-42],
        [9.2374e-42, 1.0224e-41, 8.6993e-42, 8.9683e-42]])
None
None


/usr/local/lib/python3.7/dist-packages/torch/_tensor.py:1083: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at  aten/src/ATen/core/TensorBody.h:477.)
  return self._grad
